name = "Frog O'Clock"
template = "pico8"
code = "main.lua"
[[sprite_sheet]] # 0
path = "title-background.png"
[[sprite_sheet]] # 1
path = "main-character.png"
sprite_size = [16, 16]
sprite_counts = [13, 1]
# [[map]] # 0
# path = "outside-2.tmx"
# path = "over-world2.world"
# [[map]] # 1
# path = "inside.tmx"
# [[map]] # 2
# path = "Lillys house inside.tmx"
# [[map]] # 3
# path = "Lillys house outside.tmx"
# [[map]] # 4
# path = "black smith inside town.tmx"
# [[map]] # 5
# ldtk = "table2.tmx"
