name = "Frog o'clock"
template = "pico8"
code = "main.lua"
[palette]
path = "1bit-palette.png"
[[sprite_sheet]] # 0
path = "title-background.png"
[[sprite_sheet]] # 1
path = "main-character.png"
sprite_size = [16, 16]
sprite_counts = [13, 1]
[[sprite_sheet]] # 2
path = "dream-path.png"
[[sprite_sheet]] # 3
path = "frog.png"
sprite_size = [32, 32]
sprite_counts = [8, 1]
[[sprite_sheet]] # 4
path = "character-portrait.png"
sprite_size = [16, 16]
sprite_counts = [5, 1]
[[sprite_sheet]] # 5 (collision map)
path = "dream-path.png"
indexed = true
[[sprite_sheet]] # 6
path = "fight-screen.png"
sprite_size = [128, 128]
sprite_counts = [3, 1]
[[sprite_sheet]] # 7
path = "health-bar-2.png"
sprite_size = [64, 8]
sprite_counts = [2, 1]
[[sprite_sheet]] # 8
path = "sword.png"
sprite_size = [16, 16]
sprite_counts = [1, 1]
[[sprite_sheet]] # 9
path = "button.png"
sprite_size = [16, 16]
sprite_counts = [4, 1]
[[sprite_sheet]] # 10
path = "ball frog fight.png"
sprite_size = [16, 16]
sprite_counts = [2, 1]
[[sprite_sheet]] # 11
path = "bettys house.png"
sprite_size = [128, 128]
sprite_counts = [3, 1]
[[sprite_sheet]] # 12
path = "room-blocker.png"
indexed = true
[[audio_bank]]
paths = ["boop.ogg", "ehh.ogg", "sword-swing0.ogg"]
# [[map]] # 0
# path = "outside-2.tmx"
# path = "over-world2.world"
# [[map]] # 1
# path = "inside.tmx"
# [[map]] # 2
# path = "Lillys house inside.tmx"
# [[map]] # 3
# path = "Lillys house outside.tmx"
# [[map]] # 4
# path = "black smith inside town.tmx"
# [[map]] # 5
# ldtk = "table2.tmx"
