name = "Frog o'clock"
template = "pico8"
code = "main.lua"
[palette]
path = "1bit-palette.png"
[[image]] # 0
path = "title-background.png"
[[image]] # 1
path = "main-character.png"
sprite_size = [16, 16]
# sprite_counts = [13, 1]
indexed = true
[[image]] # 2
path = "dream-path.png"
indexed = true
[[image]] # 3
path = "frog.png"
sprite_size = [32, 32]
# sprite_counts = [8, 1]
[[image]] # 4
path = "character-portrait.png"
sprite_size = [16, 16]
# sprite_counts = [5, 1]
[[image]] # 5 (collision map)
path = "dream-path.png"
indexed = true
[[image]] # 6
path = "fight-screen.png"
sprite_size = [128, 128]
# sprite_counts = [3, 1]
[[image]] # 7
path = "health-bar-2.png"
sprite_size = [64, 8]
# sprite_counts = [2, 1]
[[image]] # 8
path = "sword.png"
sprite_size = [16, 16]
# sprite_counts = [1, 1]
[[image]] # 9
path = "button.png"
sprite_size = [16, 16]
# sprite_counts = [4, 1]
[[image]] # 10
path = "ball frog fight.png"
sprite_size = [16, 16]
# sprite_counts = [2, 1]
[[image]] # 11
path = "bettys house.png"
sprite_size = [128, 128]
# sprite_counts = [3, 1]
[[image]] # 12
path = "room-blocker.png"
indexed = true
[[image]] # 13
path = "house.png"
[[image]] # 14
path = "shop.png"
[[image]] # 15
path = "shop interior.png"

[[audio_bank]]
paths = ["boop.ogg", #0
"ehh.ogg",           #1
"sword-swing0.ogg",  #2
"fight-build.ogg",   #3
"ambient-bagomp.ogg",#4
"ui-move.ogg",       #5
"ui-click.ogg",      #6
"ui-cancel.ogg",     #7
"bonk.ogg",          #8
]
# [[map]] # 0
# path = "outside-2.tmx"
# path = "over-world2.world"
# [[map]] # 1
# path = "inside.tmx"
# [[map]] # 2
# path = "Lillys house inside.tmx"
# [[map]] # 3
# path = "Lillys house outside.tmx"
# [[map]] # 4
# path = "black smith inside town.tmx"
# [[map]] # 5
# ldtk = "table2.tmx"
